### ISSUE TITLE
Help with string expansion

### ISSUE THREAD

**Issue by DesiCow** [BlitzOffline/StringExpansion#1]
Hello,

I have this string : `12.34.56.78` for example, and I would like to return the output before the 2nd dot in this string, so it should return 
`12.34` 
Can you help me how can I achieve this with your expansion?

**Comment by BlitzOffline** [comment]
Hello. Sorry for the late reply. I haven't had time to look at this expansion in a while. I'm afraid this expansion is a bit limited and has no functionality like this (yet at least). I really recommend you look into the STR expansion instead. Much more complex with a lot more features: https://github.com/sileence114/Str-Expansion https://api.extendedclip.com/expansions/str/
