### ISSUE TITLE
Version 1.0.2 shows itself as 1.0.1 - Papi thinks its outdated

### ISSUE THREAD

**Issue by CloudeLecaw** [BlitzOffline/StringExpansion#10]
![image](https://github.com/BlitzOffline/StringExpansion/assets/12080017/748ff658-d02e-469c-b054-90348e9f0343)

If you download this one or use the ecloud command after papi reload you see that it installes just version 1.0.1 (or may versioninformation was not changed in 1.0.2?)
The files on manually download is called 1.0.2 (it might be done by placeholderapi itself..)

in result PlaceholderAPI allways tells us in loading there is an Update of String.

![image](https://github.com/BlitzOffline/StringExpansion/assets/12080017/197c249a-885d-4165-a9a3-d448e554f219)
![image](https://github.com/BlitzOffline/StringExpansion/assets/12080017/ca6a7c9e-1f8a-4732-9a6f-e1edad37ea6f)

Would be nice if you may could fix this or may reuplaod a 1.0.2 to the Papi ecloud :-)

**Comment by BlitzOffline** [comment]
It seems that the internal version was not updated. The ECloud does not allow me to re-upload an older version of an expansion unfortunately but I will update the expansion to version 1.0.3 and make sure the internal version matches. Thanks for confirming. I will close this thread with a message when it is done.

**Comment by BlitzOffline** [comment]
Updated the expansion on the ecloud. Also I've added 2 new placeholders: https://api.extendedclip.com/expansions/string/versions/string-103/
