### ISSUE TITLE
Supporting Negative Indexes in Substring

### ISSUE THREAD

**Issue by TheArmagan** [BlitzOffline/StringExpansion#14]
Here is the examples:
`%string_substring_-2_helloworld%`: `ld`
`%string_substring_0,-2_helloworld%`: `hellowor`
`%string_substring_2,-2_helloworld%`: `llowor`

**Comment by BlitzOffline** [comment]
Added in:

https://api.extendedclip.com/expansions/string/versions/string-104/
https://github.com/BlitzOffline/StringExpansion/commit/6fd69f490c22a6ae88ffa08ad11b15bcb89eb3b5
