### ISSUE TITLE
null error

### ISSUE THREAD

**Issue by PixellPioneer** [BlitzOffline/StringExpansion#15]
It doesn't appear that the expansion is working for me. I have included the error down below.

and here is the placeholder/command 
`/papi parse me %string_uppercase_{cloudnet_uid}%`
`%string_uppercase_{cloudnet_uid}%`

https://mcpaste.io/8c23fab95d9b0dd1

**Comment by BlitzOffline** [comment]
Hmm. It seems that you are missing the `separator` option from config. For now, you can add `separator: "_"` in `plugins/PlaceholdersAPI/config.yml` under the `string:` option. I will release a fix for this soon.

**Comment by BlitzOffline** [comment]
Fixed in: 5043e6ef74199b75f67bfc7fcffb01bc025e945e
Can be downloaded from: https://api.extendedclip.com/expansions/string/versions/string-106/
