### ISSUE TITLE
String count dont work/appears

### ISSUE THREAD

**Issue by Mdsh9** [BlitzOffline/StringExpansion#9]
The placeholder %string_count_<string>_<match-character>%
 Dont appears and its not working.
 
 
![image](https://github.com/BlitzOffline/StringExpansion/assets/113609845/1bf4508d-23eb-48ea-85fe-54361ac39514)

**Comment by Mdsh9** [comment]
![image](https://github.com/BlitzOffline/StringExpansion/assets/113609845/fb50a11a-d8ad-4623-82f3-7309094465bc)

dump from PlaceholderAPI

https://paste.helpch.at/botehepeci

**Comment by BlitzOffline** [comment]
Thank you for the report. It seems like I've actually never posted the new version on the ecloud. Will do that today.

**Comment by BlitzOffline** [comment]
Solved: https://api.extendedclip.com/expansions/string/versions/string-102/
Should note that the placeholder was changed to the following:
`%string_occurences_count_<string>_<match>% - Counts how many times a character or a string appears in another string.`
